### ISSUE TITLE
holmies feedback (Camilla Cheng & Lisa Ye)

### ISSUE THREAD

**Issue by camillac** [bhavrish/ogmazesolver#2]
We apologize for the late feedback. :(

---
- statement of a problem
    - 
    - Are you expecting a "yes" or "no"? As a string? Or are you expecting something else? Please specify!
    - Please proofread.
---
- recursive abstraction
    -
    - Solve a maze of size what?
    - Try to follow the format that the recursive abstraction normally is in!
    - What do you mean by "solve the maze"? Use the language that you used in "statement of a problem"!
---
- base cases
    -
    - What if the explorer begins on a wall and there is no hallway?
---
- English or pseudocode description of algorithm
    - 
    - Your algorithm repeats a lot of things that could be solved by the *recursive abstraction~*. It does the same problem with a different direction each time.
    - What constitutes as a junction? When all 4 sides have hallways, or when there is more than one hallway to go toward.
   - Also, how do you handle a straight pathway maze that has a size greater than 1. Your algorithm never deals with mazes that are bigger than 1 but have no junctions.
   - Your algorithm never returns anything that solves the problem. How will going through the maze eventually answer the question?
   - Related to the previous feedback, include the treasure somewhere in the algorithm! Your algorithm goes through the maze, but never checks whether or not there is a path to the treasure!

**Comment by lisaye1221** [comment]
Adding on to the recursive abstraction: 

I think you're on the right track in terms of dividing the problem into a smaller problem.
But in this case, asking the recursive abstraction to find a path to the treasure of a smaller maze doesn't really make sense to me. I think we shouldn't modify the maze. Also it isn't really clear to me what a maze of size "n-1 hallway" looks like. What does hallway mean? A stepping stone or a whole rank/file?

**Comment by lisaye1221** [comment]
About the pseudocode:

I suggest converting this English into code format so it will be very easy to code when it is time.
Checking if the player is at a "junction" requires a whole lot of code. 
I assume by junction you mean when all 4 direction of the current spot is a stepping stone. 
I don't think that is necessary to check though, it is too complicated. 
I suggest to treat every spot as a "junction" and check all 4 spots in each direction as you have described and let the recursive backtracking do the trick. Hope that makes sense.
